## excel sheet headers
tc_id = 'TC ID'
tc_description = 'Description'
tc_name = 'Name'
tc_test_data = 'Test Data'
tc_request_name = 'Transaction Type'
tc_rule_id = 'Rule ID'
tc_objective = 'Objective (Expected Result)'
tc_precondition = 'Precondition'
tc_object = 'Object'
tc_element = 'Element'
tc_error_text = 'Error Text'
tc_scenario_type = 'Scenario Type'
tc_dependency = 'Dependency'
tc_dependency_variables = 'Dependency Variables'
tc_skip_env1 = 'Skip Env 1'
tc_occurrences = 'Occurrences'
tc_field_value = 'Field Value'
tc_additional_reference = 'Additional Reference'

## xml tags
old_system_tag = '{https://www.shafafiya.org/v2/}'
new_system_tag = '{https://www.shafafiya.org/v2/}'
